name:                parsatog
version:             0.1.0.0
github:              "KZhide/parsatog"
license:             BSD3
author:              "K_Zhide"
maintainer:          "K.WildBoar@gmail.com"
copyright:           "2018 K_Zhide"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/KZhide/parsatog#readme>

dependencies:
- base >= 4.7 && < 5
- parsec >= 3.1 && < 4

library:
  source-dirs: src

executables:
  parsatog-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - parsatog

tests:
  parsatog-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - parsatog
